version: "3.8"
services:
  zookeeper:
    image: "bitnami/zookeeper:latest"
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: "bitnami/kafka:latest"
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      - KAFKA_CFG_BROKER_ID=1
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://local-kafka:9092,PLAINTEXT_HOST://127.0.0.1:29092
    container_name: local-kafka
    depends_on:
      - zookeeper
  mysql_write:
    image: mysql:8.0
    command: mysqld
    environment:
      MYSQL_DATABASE: cqrs_es_example_blog_write_database
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./mysql_write/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql_write/init.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "--password=$$DB_PASSWORD",
        ]
      interval: 20s
      timeout: 10s
      retries: 10
  debezium:
    image: "debezium/connect:2.0"
    ports:
      - "8083:8083"
    environment:
      - BOOTSTRAP_SERVERS=local-kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=_kafka_connect_configs
      - OFFSET_STORAGE_TOPIC=_kafka_connect_offsets
      - STATUS_STORAGE_TOPIC=_kafka_connect_statuses
    depends_on:
      - zookeeper
      - kafka
      - mysql_write
  mysql_read:
    image: mysql:8.0
    command: mysqld
    environment:
      MYSQL_DATABASE: cqrs_es_example_blog_read_database
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./mysql_read/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql_read/init.d:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "--password=$$DB_PASSWORD",
        ]
      interval: 20s
      timeout: 10s
      retries: 10
  command_api:
    build:
      context: .
      dockerfile: ./command/Dockerfile
    ports:
      - "3000:3000"
    tty: true
    depends_on:
      mysql_write:
        condition: service_healthy
  query_api:
    build:
      context: .
      dockerfile: ./query/Dockerfile
    ports:
      - "3001:3001"
    tty: true
    depends_on:
      mysql_read:
        condition: service_healthy
  read_model_updater:
    build:
      context: .
      dockerfile: ./read_model_updater/Dockerfile
    ports:
      - "3002:3002"
    depends_on:
      mysql_read:
        condition: service_healthy
      debezium:
        condition: service_started
    restart: always
  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    ports:
      - "4000:4000"
    tty: true